
#define DEVICE_ID 3

//#define HEALTH
//#define AMMO
//#define FLAG_RED
//#define FLAG_BLUE

#ifdef HEALTH
  #define IR_ADDRESS (IR_ADDRESS_HEALTH)
  #define IR_COMMAND DEVICE_ID
  #define MSG_TYPE_PING (MSG_TYPE_HEALTH_DISPENSER_PING)
  #define IS_DISPENSER
#elif defined(FLAG_RED)
  #define IR_ADDRESS (IR_ADDRESS_FLAG)
  #define IR_COMMAND 0
  #define MSG_TYPE_PING (MSG_TYPE_FLAG_PING)
  #define IS_FLAG
#elif defined(FLAG_BLUE)
  #define IR_ADDRESS (IR_ADDRESS_FLAG)
  #define IR_COMMAND 1
  #define MSG_TYPE_PING (MSG_TYPE_FLAG_PING)
  #define IS_FLAG
#else
  #define IR_ADDRESS (IR_ADDRESS_AMMO)
  #define IR_COMMAND DEVICE_ID
  #define MSG_TYPE_PING (MSG_TYPE_AMMO_DISPENSER_PING)
  #define IS_DISPENSER
#endif

#define MSG_TYPE_SERVER_PING 1
#define MSG_TYPE_HEALTH_DISPENSER_PING 45
#define MSG_TYPE_AMMO_DISPENSER_PING 46
#define MSG_TYPE_FLAG_PING 47

#define MSG_TYPE_IN_DISPENSER_USED 51
#define MSG_TYPE_IN_DISPENSER_SET_TIMEOUT 53
#define MSG_TYPE_IN_FLAG_STATE 54

#define FLAG_STATE_OFF 0
#define FLAG_STATE_ON 1

#define STATE_IDLE 0
#define STATE_AVAILABLE 1
#define STATE_OFFLINE 2

#define CONNECTION_STATUS_LED 2
#define MAIN_LIGHT_LED 4
#define IR_LED_PIN 13

#define IR_ADDRESS_GUN 0
#define IR_ADDRESS_RESPAWN 1
#define IR_ADDRESS_HEALTH 2
#define IR_ADDRESS_AMMO 3
#define IR_ADDRESS_FLAG 4

